<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Vsledky vyhadvania_decoration-backgrou_515444</name>
   <tag></tag>
   <elementGuidId>4d6a0620-9d97-4a3e-921d-cb1c336285f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ThemeNavigationItem-idm46152708037392423836227980960-1']/div/div/div/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.decoration-background-image.image-rendering.image-background.left.decoration-none.border</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>decoration-background-image image-rendering image-background  left decoration-none border</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-retina</name>
      <type>Main</type>
      <value>/images/salvia_officinalis_k9_trvalka_salvia_k9_c7b529c46cfd2f7b@2x.png</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Salvia officinalis k9 Trvalka šalvia k9</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ThemeNavigationItem-idm46152708037392423836227980960-1&quot;)/div[@class=&quot;ThemeNavigationInit&quot;]/div[@class=&quot;ThemeNavigationInitBlock relative nooverflow&quot;]/div[@class=&quot;themenavigation_image inline-block relative&quot;]/a[@class=&quot;relative left block decoration-none effect background-contain&quot;]/span[@class=&quot;decoration-background-image image-rendering image-background  left decoration-none border&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ThemeNavigationItem-idm46152708037392423836227980960-1']/div/div/div/a/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Výsledky vyhľadávania'])[1]/following::span[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Akcie'])[2]/following::span[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trvalka šalvia k9'])[1]/preceding::span[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/a/span</value>
   </webElementXpaths>
</WebElementEntity>
