<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_skSloveninaAfrikaansazrbaycanbosanskica_5fa998</name>
   <tag></tag>
   <elementGuidId>5054ec51-5ebe-4da7-9957-87de5839ef4c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='xe7COe']/div[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.jw8mI</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jw8mI</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>sk‪Slovenčina‬‪Afrikaans‬‪azərbaycan‬‪bosanski‬‪català‬‪Čeština‬‪Cymraeg‬‪Dansk‬‪Deutsch‬‪eesti‬‪English (United Kingdom)‬‪English (United States)‬‪English‬‪Español (España)‬‪Español (Latinoamérica)‬‪euskara‬‪Filipino‬‪Français (Canada)‬‪Français (France)‬‪Gaeilge‬‪galego‬‪Hrvatski‬‪Indonesia‬‪isiZulu‬‪íslenska‬‪Italiano‬‪Kiswahili‬‪latviešu‬‪lietuvių‬‪magyar‬‪Melayu‬‪Nederlands‬‪norsk‬‪o‘zbek‬‪polski‬‪Português (Brasil)‬‪Português (Portugal)‬‪română‬‪shqip‬‪slovenščina‬‪srpski (latinica)‬‪Suomi‬‪Svenska‬‪Tiếng Việt‬‪Türkçe‬‪Ελληνικά‬‪беларуская‬‪български‬‪кыргызча‬‪македонски‬‪монгол‬‪Русский‬‪српски (ћирилица)‬‪Українська‬‪ქართული‬‪қазақ тілі‬‪հայերեն‬‫עברית‬‫اردو‬‫العربية‬‫فارسی‬‪አማርኛ‬‪नेपाली‬‪मराठी‬‪हिन्दी‬‪বাংলা‬‪ਪੰਜਾਬੀ‬‪ગુજરાતી‬‪தமிழ்‬‪తెలుగు‬‪ಕನ್ನಡ‬‪മലയാളം‬‪සිංහල‬‪ไทย‬‪ລາວ‬‪မြန်မာ‬‪ខ្មែរ‬‪한국어‬‪中文（香港）‬‪日本語‬‪简体中文‬‪繁體中文‬Prihlásiť saNež prejdete do Vyhľadávania GoogleGoogle pomocou súborov cookie a údajov:poskytuje a udržuje služby, napríklad sleduje výpadky a chráni pred spamom, podvodmi a zneužitím;meria zapojenie publika a štatistiky webu, aby pochopil, ako sa jeho služby používajú.Ak súhlasíte, pomocou súborov cookie a údajov tiež budeme:zlepšovať kvalitu našich služieb a vyvíjať nové;zobrazovať reklamy a merať ich efektívnosť;v závislosti od vašich nastavení zobrazovať prispôsobený obsah;v závislosti od vašich nastavení zobrazovať prispôsobené alebo všeobecné reklamy na Googli a internete.Zobrazovaný neprispôsobený obsah a reklamy môžu byť ovplyvňované napríklad aktuálne prehliadaným obsahom alebo vašou polohou (zobrazovanie reklám je založené na všeobecnej polohe). Prispôsobený obsah a reklamy môžu byť založené na týchto informáciách a vašej aktivite, napríklad vyhľadávaniach Google a videách, ktoré ste pozerali na YouTube. Prispôsobený obsah a reklamy zahŕňajú napríklad relevantnejšie výsledky a odporúčania, prispôsobenú domovskú stránku YouTube a reklamy, ktoré sú upravené na mieru podľa vašich záujmov.Kliknutím na Prispôsobiť si prezrite možnosti vrátane ovládania umožňujúceho odmietnuť prispôsobovanie pomocou súborov cookie a informácie o ovládaní na úrovni prehliadača umožňujúce odmietnuť používanie niektorých či všetkých súborov cookie na iné účely. Tiež môžete kedykoľvek prejsť na g.co/privacytools.Ochrana súkromia·Zmluvné podmienkyPrispôsobiťSúhlasím</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xe7COe&quot;)/div[@class=&quot;jw8mI&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='xe7COe']/div[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tmavý motív: vypnutý'])[1]/following::div[7]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Odoslať spätnú väzbu'])[1]/following::div[10]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[3]</value>
   </webElementXpaths>
</WebElementEntity>
